### ISSUE TITLE
7/15 - 7/19: Login System

### ISSUE THREAD

**Issue by PaarasPurohit** [nighthawkcoders/portfolio_2025#25]
# Overview

This week, I set up the new Spring 2025 project with a user database. I also made a login page that uses the Spring backend instead of the Flask one. The biggest challenge was on the frontend, figuring out how to make the requests with pre-existing syntax.

# Tasks

### Backend

- [x] Set up repository and debugged all configuration issues - **1 Hour**
- [x] Created the user database, complete with a POJO, JPA repository, API controller, DTO, and service class. - **1 Hour**
- [x] Set up a new `PostMapping` method that handles user login - **1 Hour**
- [ ] Set up a new `PostMapping` method that handles user account creation
- [ ] Created a database for sessions the same way the user database was created
- [ ] Set up a new `PostMapping` method that handles booking a session from student side
- [ ] Set up a new `PostMapping` method that handles booking a session from teacher side
- [ ] Set up a new `DeleteMapping` method that handles removing a completed session
- [ ] Debugging and deployment

### Frontend

- [x] Interpreted all syntax, variables used, and structure of new portfolio, created files and configured environment for logging in with Spring - **1 Hour**
- [x] Restarted the fetch method for logging in to work with the Spring system - **1 Hour**
- [ ] Restarted the fetch method for signing up to work with the Spring system
- [ ] Created page for booking a session (student side)
- [ ] Created page for booking a session (teacher side)
- [ ] Created POST request for booking a session (student side)
- [ ] Created POST request for teachers, interns, etc. to take a student's session
- [ ] Debugging and deployment

# Key Commits

### Backend

In `User.java`, I made the following fields to match the model in the Flask backend. Constructors and the `init` method followed suit:
<img src="https://github.com/user-attachments/assets/125a55b3-73ad-42b8-bf56-73a535c4c1b6" width=50%>

In the `user` folder, the repository, service, and DTO classes stayed default, but in the API controller, I made from scratch the `PostMapping` authentication method:
<img src="https://github.com/user-attachments/assets/500e5777-a699-4113-8ff0-80aeef520ef3" width=75%>

### Frontend

I made `login-spring.md` and `spring-login.js` two separate files and referenced the script accordingly in `login-spring.md`. For `spring-login.js`, I created a custom request method that worked with the `PostMapping` method in the backend:
<img src="https://github.com/user-attachments/assets/f1e57073-fb6d-47b2-935d-a3f0c1438712" width=75%>
