### ISSUE TITLE
7/22 - 7/26: Session Database

### ISSUE THREAD

**Issue by PaarasPurohit** [nighthawkcoders/portfolio_2025#37]
# Overview

This week was rather slow since I was only able to work on the backend balancing with other commitments, but I did get done with the session database, which is fundamental for students who will need to book appointments for office hours.

# Tasks

### Backend

- [x] Set up the repository and debugged all configuration issues - **1 Hour**
- [x] Created the user database with a POJO, JPA repository, API controller, DTO, and service class. - **1 Hour**
- [x] Set up a new `PostMapping` method that handles user login - **1 Hour**
- [ ] Set up a new `PostMapping` method that handles user account creation
- [x] Created a database for sessions the same way the user database was created **3 Hours**
- [x] Set up a new `PostMapping` method that handles booking a session from the student side **2 Hours**
- [x] Set up a new `PostMapping` method that handles booking a session from teacher's side **2 Hours**
- [ ] Set up a new `DeleteMapping` method that handles removing a completed session
- [ ] Debugging and deployment

### Frontend

- [x] Interpreted all syntax, variables used, and structure of the new portfolio, created files, and configured environment for logging in with Spring - **1 Hour**
- [x] Restarted the fetch method for logging in to work with the Spring system - **1 Hour**
- [ ] Restarted the fetch method for signing up to work with the Spring system
- [ ] Created a page for booking a session (student side)
- [ ] Created a page for booking a session (teacher side)
- [ ] Created POST request for booking a session (student side)
- [ ] Created POST request for teachers, interns, etc. to take a student's session
- [ ] Debugging and deployment

# Key Commits

### Backend

In `Session.java`, I made the following fields that users of any role can fulfill. Constructors and the `init` method followed suit:
<img src="https://github.com/user-attachments/assets/22a18ee1-f080-443c-86a4-4b94c85d9833" width=75%>

In the `session` folder, the repository, service, and DTO classes stayed default, but in the API controller, I made the `PostMapping` `assignTutor()` method from scratch. It'll be called whenever a teacher assigns a tutor to a student's booked session:
<img src="https://github.com/user-attachments/assets/58779c26-e17f-4e12-a3b7-975891e26c67" width=100%>

In `SessionAPIController.java`, I created a `GetMapping` method called `getSessionsByTutor()` that takes in the user ID as its tutor ID, then returns all sessions with that ID. This is used by tutors when they log in and see upcoming sessions. However, since students will also be making an account, I'll also be making a `getSessionsByUser()` method that does the same thing, but for users:
<img src="https://github.com/user-attachments/assets/99c9a023-ea18-4de7-ae82-4425f519c366" width=100%>

Above, when the `sessionService.getSessionsByAssignedTutor(assignedTutor)` method is called, it references `findByAssignedTutor(String assignedTutor)` in `SessionJPARepository.java`:
<img src="https://github.com/user-attachments/assets/a1609b79-159b-4a10-a7a1-1715d58ee4b8" width=75%>
